# docker file for local-development
#
FROM postgres:16

# packages and extensions
#
RUN apt-get update \
    && apt-get install -y \
    postgresql-16-pgtap \
    postgresql-16-cron \
    postgresql-16-partman \
    postgresql-16-postgis-3 \
    postgresql-plpython3-16 \
    libpq-dev \
    gdal-bin

# get python modules
#
RUN apt-get install -y \
    python3-numpy \
    python3-scipy \
    python3-sympy \
    python3-httpx \
    python3-feedparser \
    python3-cloudpickle


# below does not seem to work with python 3.11
# COPY requirements.txt /requirements.txt
# RUN pip3 install -r /requirements.txt


# create database
#
COPY ./create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/

# added test-manager
#
COPY test.sql /test.sql

# work directory
#
WORKDIR /work
