# docker file for local-development
#
FROM postgres:15

# packages and extensions
#
RUN apt-get update \
    && apt-get install -y \
        postgresql-15-pgtap \
        postgresql-15-cron \
        postgresql-15-partman \
        postgresql-15-postgis-3 \
        postgresql-plpython3-15 \
        libpq-dev \
        python3-pip \
        gdal-bin \
        git \
        jq

# build python modules
#
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

# some files
#
COPY ./create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/
COPY test.sql /test.sql

# work directory
#
WORKDIR /work
